include ../../config/makeconfig

OBJ = \
clbas.o \
bas_bind.o \
bas_sph2ang1.o \
bas_ang2sph1.o \
bas_sph2ang2.o \
bas_ang2sph2.o \
bas_gen_alph.o \
bas_gen_pmat.o \
bas_gen_kmat.o \
bas_gen_tmat.o \
bas_gen_d2ll.o \
bas_gen_zfac.o \
bas_gen_pzfac.o \
bas_gen_azfac.o \
bas_gen_d2fac.o \
bas_pp_init.o \
bas_pp_final.o \
bas_pp_hgh.o \
bas_pp_trailneeds.o \
bas_pp_trailneeds_num.o \
bas_pp_oncvpsp.o \
bas_pp_tmpsp.o \
bas_pp_genkb.o \
bas_sph2ang2_ecs.o \
bas_ang2sph2_ecs.o \
bas_gen_d1mat.o \

#old bas_get_funang.o \
#old bas_put_funang.o \
#old bas_add_funang.o \
#old bas_get_funsph1.o \
#old bas_put_funsph1.o \
#old bas_add_funsph1.o \
#old bas_get_funsph2.o \
#old bas_put_funsph2.o \
#old bas_add_funsph2.o \

include $(TD1C_CON)/make.objcomp
