include ../../config/makeconfig

OBJ = \
futil_diag_comp.o \
futil_gdiag_comp.o \
futil_exphd.o \
futil_gexphd.o \
futil_gmatinv.o \
futil_index_double.o \
futil_matinv_reg.o \
futil_hforb_read.o \

include $(TD1C_CON)/make.objcomp
