include ../../config/makeconfig

OBJ = \
integ_trap.o\
integ_simpson.o\
integ_CN.o\
integ_EI.o\
surff_init.o \
surff_prop.o \
surff_phys.o \
calc_orb.o \
surff_rec_v2xmat.o \

include $(TD1C_CON)/make.objcomp
