include ../../config/makeconfig

OBJ = \
util.o \
util_blas.o \
util_get_labs.o \
util_get_dabs.o \
util_get_cabs.o \
util_expax.o \
util_det.o \
util_ifact.o \
util_bicoeff.o \
util_trimat.o \
util_window.o \
util_fact.o \
util_3j000.o \
util_omp_disp.o \
util_omp_nproc.o \
util_omp_iproc.o \
util_omp_gather.o \
util_matout.o \
util_krylov.o \
util_arnoldi.o \
util_svd.o \
util_youla.o \
util_diag.o \
util_print_vec.o \
util_matinv_reg.o \
util_gmatinv.o 

include $(TD1C_CON)/make.objcomp
