include ../../config/makeconfig

OBJ = \
lapack_sv.o \
lapack_ev.o \
zclear_omp.o \
zcopy_omp.o \
zscal_omp.o \
zxpy_omp.o \
zxpyz_omp.o \
zxmyz_omp.o \
zaxpy_omp.o \
zaxpyz_omp.o \
zaxpbyz_omp.o \
zdotc_omp.o \
zadd_omp.o \

include $(TD1C_CON)/make.objcomp
