include ../../config/makeconfig

OBJ = \
mod_const.o \
mod_control.o \
mod_rad.o \
mod_sph.o \
mod_ormas.o \
mod_bas.o \
mod_hprod.o \
mod_op1tr.o \
mod_expokit.o \
mod_pes.o \
mod_hprod.o \
mod_h1rat.o \
mod_ppatom.o \
mod_oncvpsp.o \
mod_tmpsp.o \
mod_cc.o \
mod_cc2.o \

include $(TD1C_CON)/make.objcomp
