////////////////////////////////////////////////////////////////////////
// fortran interfaces
////////////////////////////////////////////////////////////////////////
// ##### DO NOT touch lines // START and // END #####
////////////////////////////////////////////////////////////////////////
#ifndef __F90_WRAPPER__
#define __F90_WRAPPER__
////////////////////////////////////////////////////////////////////////
extern "C"
{
// START
void bas_ang2sph1_(const dcomplex*, dcomplex*);
void bas_ang2sph1_dyn_(const dcomplex*, dcomplex*);
void bas_ang2sph1_dyn3j_(const dcomplex*, const dcomplex*, dcomplex*);
void bas_ang2sph1_dyn_radfc_(const dcomplex*, dcomplex*);
void bas_ang2sph1_fc_(const dcomplex*, dcomplex*);
void bas_ang2sph1_fc1_(const dcomplex*, dcomplex*);
void bas_ang2sph1_fc2_(const dcomplex*, dcomplex*);
void bas_ang2sph1_radfc_(const dcomplex*, dcomplex*);
void bas_ang2sph2_(const dcomplex*, dcomplex*);
void bas_ang2sph2_dyn_(const dcomplex*, dcomplex*);
void bas_ang2sph2_dyn3j_(const dcomplex*, const dcomplex*, dcomplex*);
void bas_ang2sph2_fc_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc1_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc1dyn_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc1dyn3j_(const dcomplex*, const dcomplex*, dcomplex*);
void bas_ang2sph2_fc1fc1_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc2_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc2dyn_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc2fc1_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc2fc2_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fcdyn_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fcfc_(const dcomplex*, dcomplex*);
void bas_ang2sph2one_(const int*, const dcomplex*, dcomplex*);
void bas_ang2sph2_dyn_ecs_(const dcomplex*, dcomplex*);
void bas_ang2sph2_fc1dyn_ecs_(const dcomplex*, dcomplex*);
void bas_gen_alph_();
void bas_gen_azfac_();
void bas_gen_d1mat_(dcomplex*);
void bas_gen_d2fac_();
void bas_gen_d2ll_(double*);
void bas_gen_kmat_(dcomplex*);
void bas_test_keig_(const int*, const int*, const int*, const int*, const double*, double*);
void bas_gen_pmat_(dcomplex*);
void bas_gen_pzfac_();
void bas_gen_tmat_(dcomplex*);
void bas_gen_zfac_();
void bas_pp_final_();
void bas_pp_genkb_(const dcomplex*);
void bas_pp_gen_hgh_();
void hgh_get_cloc_(const int*, double*);
void hgh_get_hproj_(const int*, double*);
void hgh_get_rloc_(const int*, double*);
void hgh_get_rproj_(const int*, double*);
void hgh_get_znuc_(const int*, double*);
void bas_pp_init_();
void bas_pp_gen_oncvpsp_();
void bas_pp_gen_tmpsp_();
void TrailNeeds_getParDF_(double*, double*);
void TrailNeeds_getParHF_(double*, double*);
void TrailNeeds_getV_(double*, double*);
void bas_pp_gen_trailneeds_();
void bas_pp_gen_trailneeds_num_();
void bas_sph2ang1_(const dcomplex*, dcomplex*);
void bas_sph2ang1_dyn_(const dcomplex*, dcomplex*);
void bas_sph2ang1_dyn3j_(const dcomplex*, dcomplex*, dcomplex*);
void bas_sph2ang1_dyn_radfc_(const dcomplex*, dcomplex*);
void bas_sph2ang1_fc_(const dcomplex*, dcomplex*);
void bas_sph2ang1_fc3j_(const dcomplex*, dcomplex*, dcomplex*);
void bas_sph2ang1_radfc_(const dcomplex*, dcomplex*);
void bas_sph2ang2_(const dcomplex*, dcomplex*);
void bas_sph2ang2_dyn_(const dcomplex*, dcomplex*);
void bas_sph2ang2_dyn3j_(const dcomplex*, dcomplex*, dcomplex*);
void bas_sph2ang2_fc_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc1_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc1dyn_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc1dyn3j_(const dcomplex*, dcomplex*, dcomplex*);
void bas_sph2ang2_fc1fc1_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc2_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc2dyn_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc2fc1_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc2fc2_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fcdyn_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fcfc_(const dcomplex*, dcomplex*);
void bas_sph2ang2one_(const int*, const dcomplex*, dcomplex*);
void bas_sph2ang2_dyn_ecs_(const dcomplex*, dcomplex*);
void bas_sph2ang2_ecs_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fc1dyn_ecs_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fcdyn_ecs_(const dcomplex*, dcomplex*);
void bas_sph2ang2_fcfc_ecs_(const dcomplex*, dcomplex*);
void control_xc_final_();
void control_xc_init_(const int*);
void futil_diag_comp_(const bool*, const int*, dcomplex*, dcomplex*);
void futil_exphd_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void futil_exphd_cutoff_(const int*, const dcomplex*, const double*, const dcomplex*, dcomplex*);
void futil_gdiag_comp_(const bool*, const int*, dcomplex*, dcomplex*, dcomplex*);
void futil_gexphd_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void futil_gmatinv_(const int*, const double*, const dcomplex*, dcomplex*);
void futil_hforb_read_(const int*, const int*, const int*, dcomplex*);
void futil_index_double_(const bool*, const int*, const double*, int*);
void futil_matinv_reg_(const int*, const double*, const dcomplex*, dcomplex*);
void hprod_addfc_tmat_();
void hprod_azprod_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
void hprod_azprod_all_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_azprod_dyn_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_azprod_fc_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_azprod_fc1_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_azprod_fc2_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_azprodp_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
void hprod_bind_(const double*, const double*, const double*, const double*, const double*, const double*, const double*, const double*, const bool*, const double*);
void hprod_chkconv_(const double*, const dcomplex*, const dcomplex*, double*, double*);
void hprod_cidiag_(const dcomplex*, dcomplex*);
void hprod_cidiagx_(dcomplex*);
void hprod_dipole_(const double*, const dcomplex*, const dcomplex*, double*, double*, double*);
void hprod_dipole_ion_(const int*, const double*, const double*, const dcomplex*, const dcomplex*, double*, double*, double*);
void hprod_dipole_ipd_(const int*, const double*, const double*, const dcomplex*, const dcomplex*, double*, double*, double*);
void hprod_dipole_ipx_(const int*, const double*, const double*, const dcomplex*, const dcomplex*, double*, double*, double*);
void hprod_op1trans_(const double*, double*);
double hprod_ene_act_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
double hprod_ene_act1_(const dcomplex*, const dcomplex*);
double hprod_ene_dcore_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
double hprod_ene_dcx_();
double hprod_ene_dft1_(const dcomplex*, const dcomplex*);
double hprod_ene_fcore_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
double hprod_ene_fcx_();
void hprod_enepole_(const double*, const dcomplex*, const dcomplex*);
void hprod_enepole_old_(const double*, const dcomplex*, const dcomplex*);
void hprod_energy_(const double*, const dcomplex*, const dcomplex*);
double hprod_energy1_(const double*, const double*, const dcomplex*, const dcomplex*);
void hprod_energy_dft_(const double*, const dcomplex*);
void hprod_fc_equiv_(dcomplex*);
void hprod_final_();
void hprod_fockdiag_(const double*, dcomplex*, dcomplex*, double*);
void hprod_fockdiagx_(dcomplex*, dcomplex*, double*);
void hprod_fockdiagx2_(const int*, const int*, dcomplex*, dcomplex*, double*);
void hprod_fulldiag_(dcomplex*);
void hprod_fulldiag_diag_(const dcomplex*);
void hprod_fulldiag_fock1_(dcomplex*);
void hprod_fulldiag_fock2_(const dcomplex*, dcomplex*);
void hprod_fulldiag_fock2j_(const dcomplex*, dcomplex*);
void hprod_fulldiag_fock2k_(const dcomplex*, dcomplex*);
void hprod_fulldiag_poisson1_(const int*, const double*, dcomplex*);
void hprod_gtran_(const bool*, const double*, const int*, const dcomplex*, dcomplex*);
void hprod_gtran_ang2sph_(const int*, const dcomplex*, dcomplex*);
void hprod_gtran_sph2ang_(const int*, const dcomplex*, dcomplex*);
void hprod_get_norb_(dcomplex*, const dcomplex*, dcomplex*);
void hprod_get_norb_msep_(dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_getprojhigh_();
void hprod_getprojhigh_diag_(const dcomplex*, dcomplex*, double*);
void hprod_getden1_(dcomplex*);
void hprod_getint1_(dcomplex*);
void hprod_getint2_(dcomplex*);
void hprod_gfock_(const double*, const dcomplex*, const dcomplex*);
void hprod_gfock_nofcx_(const double*, const dcomplex*, const dcomplex*);
void hprod_gfock_sum_();
void hprod_gfock_dft_(const double*, const dcomplex*, const dcomplex*);
void hprod_h1add_(const bool*, const dcomplex*, const double*, const dcomplex*, dcomplex*);
void hprod_h1tot_(const bool*, const double*, const dcomplex*, dcomplex*);
void hprod_htot_(const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_htoto_(const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_htotx_(const double*, const double*, const dcomplex*, const dcomplex*);
void hprod_htot_dft_(const double*, const double*, const dcomplex*, dcomplex*);
void hprod_htotx_dft_(const double*, const double*, const dcomplex*);
void hprod_htot_dtorb_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_htot_getdt_(const double*);
void hprod_htoto_getdt_(const double*);
void hprod_htot_init_();
void hprod_htot_init2_();
void hprod_htot_mkxmat_aa_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_aa1_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_aa2_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_htot_mkxmat_ca_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_ca0_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_cc_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_fc_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_aa1_ecs_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_aa2_ecs_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_htot_mkxmat_ca0_ecs_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_ca_ecs_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_cc_ecs_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_mkxmat_fc_ecs_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_htot_sum_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_htot_sum0_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_htoto_sum_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_init_();
void hprod_invden_(const dcomplex*, dcomplex*, dcomplex*);
void hprod_invden_inv_(const int*, const double*, const dcomplex*, dcomplex*);
void hprod_invwrad_(dcomplex*, const int*, const int*, const int*, const int*);
void hprod_invwrad_all_(dcomplex*);
void hprod_invwrad_dyn_(dcomplex*);
void hprod_invwrad_fc_(dcomplex*);
void hprod_invwrad_fc1_(dcomplex*);
void hprod_invwrad_fc2_(dcomplex*);
void hprod_invwradp_(dcomplex*, const int*, const int*, const int*, const int*);
void hprod_ipd_(const int*, const double*, const double*, const dcomplex*, const dcomplex*, double*);
void hprod_ipx_(const int*, const double*, const double*, const dcomplex*, const dcomplex*, double*);
void hprod_kickk_(const double*, dcomplex*);
void hprod_mfprod_();
void hprod_mfprod_act2_(dcomplex*, const int*, const int*);
void hprod_mfprod_act2_ecs_(dcomplex*, const int*, const int*);
void hprod_mfprod_actj_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_actjall_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_actx_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_actxall_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_dcj_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_dcx_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_ene_();
void hprod_mfprod_fcj_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_fcx1_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_fcx2_(const bool*, dcomplex*, const int*, const int*);
void hprod_mfprod_gfock_();
void hprod_mfprod_gfock_nofcx_();
void hprod_mfprod_mp_();
void hprod_mfprod2_();
void hprod_mfprod2_act2_(const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_act2_ecs_(const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_act2v2_(const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_actj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_actj_onFC_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprod2_actjall_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_actx_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_actx_onFC_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprod2_actxall_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_dcj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod2_dcj_onFC_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprod2_dcx_(const bool*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprod2_dcx_onFC_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprod2_ene_();
void hprod_mfprod2_fcj_(const bool*, const dcomplex*, dcomplex*);
void hprod_mfprod2_fcx1_(const bool*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprod2_fcx2_(const bool*, const dcomplex*, dcomplex*);
void hprod_mfprod2_gfock_();
void hprod_mfprod2_mp_();
void hprod_mfprod3j_();
void hprod_mfprod3j_act2_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_actj_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_actj_onFC_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_actjall_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_actx_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_actx_onFC_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_actxall_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_dcj_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_dcj_onFC_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_dcx_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_dcx_onFC_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_ene_();
void hprod_mfprod3j_fcj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_fcx1_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_fcx2_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprod3j_gfock_();
void hprod_mfprod3j_mp_();
void hprod_mfprod_dftj_(const dcomplex*, const dcomplex*, dcomplex*, double*);
void hprod_mfprod_dftx_(const double*, const dcomplex*, dcomplex*, double*);
void hprod_mfprodx3j_();
void hprod_mfprodx3j_act2_(const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprodx3j_actj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprodx3j_actjall_(const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprodx3j_actx_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprodx3j_actxall_(const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprodx3j_dcj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mfprodx3j_dcj_onFC_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprodx3j_dcx_(const bool*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprodx3j_dcx_onFC_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprodx3j_ene_();
void hprod_mfprodx3j_fcj_(const bool*, const dcomplex*, dcomplex*);
void hprod_mfprodx3j_fcx1_(const bool*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mfprodx3j_fcx2_(const bool*, const dcomplex*, dcomplex*);
void hprod_mfprodx3j_gfock_();
void hprod_mfprodx3j_mp_();
void hprod_mkint1_sph_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_mkint1_sph_ecs_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_mkint1_sph_ecs2_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_mkint1_sph_inner_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_mkint2_sph_(const dcomplex*, const dcomplex*);
void hprod_mkint2_sph_ecs_(const dcomplex*, const dcomplex*);
void hprod_mkint2_sph_ecs2_(const dcomplex*, const dcomplex*);
void hprod_mkint2_x3j_(const dcomplex*, const dcomplex*);
void hprod_mkl2mat_(const dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mklzmat_(const dcomplex*, dcomplex*);
void hprod_mkovlp_(const double*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mkovlp_kshell_(const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mkovlp_shell_(const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mkovlp2_(const int*, const int*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mkovlp2p_(const int*, const int*, const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_mkrho1_(double*);
void hprod_mkrho2_();
void hprod_mkrho2_dyn_();
void hprod_mkrho2p_(const char*, const dcomplex*, dcomplex*);
void hprod_mkrho2p3j_(const char*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mkrho2_dyn_ecs_();
void hprod_mkrho2p_ecs_(const char*, const dcomplex*, dcomplex*);
void hprod_mkrho2_x3j_();
void hprod_mkrho2_x3j_dyn_();
void hprod_mkrho2p_x3j_(const char*, const dcomplex*, dcomplex*);
void hprod_mkrhoc_();
void hprod_mkrhoxc_(dcomplex*, double*);
void hprod_mkrrad_(const int*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mkrrad0_(const int*, const double*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mkrrad1_(const int*, const double*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mkrrad2_(const int*, const double*, const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mkrrad3_(const int*, const double*, const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mkrradp_(const int*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_mkrradp_old_(const int*, const dcomplex*, dcomplex*);
void hprod_mkv2mf_();
void hprod_mkv2mf_dyn_();
void hprod_mkv2mf_herm_(const char*, dcomplex*, dcomplex*);
void hprod_mkv2mf_herm3j_(const char*, dcomplex*, dcomplex*, dcomplex*);
void hprod_mkv2mf_poisson_(const char*, const dcomplex*, dcomplex*);
void hprod_mkv2mf_poissonp_(const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*, const int*, const int*, const int*);
void hprod_mkv2mf_poissonp2_(const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*, const int*, const int*, const int*);
void hprod_mkv2mf2_();
void hprod_mkv2mf2_dyn_();
void hprod_mkv2mf2_herm_(const char*, dcomplex*, dcomplex*);
void hprod_mkv2mf2_poisson_(const char*, const dcomplex*, dcomplex*);
void hprod_mkv2mf2_poissonp_(const dcomplex*, dcomplex*, const int*, const int*, const int*);
void hprod_mkv2mf2_poissonp2_(const dcomplex*, dcomplex*, const int*, const int*, const int*);
void hprod_mkv2mf_dyn_ecs_();
void hprod_mkv2mf_ecs_();
void hprod_mkv2mf_herm_ecs_(const char*, dcomplex*, dcomplex*);
void hprod_mkv2mf_poisson_ecs_(const char*, const dcomplex*, dcomplex*);
void hprod_mkv2mf_poissonp_ecs_(const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*, const int*, const int*, const int*);
void hprod_mkv2mf_x3j_();
void hprod_mkv2mf_x3j_dyn_();
void hprod_mkv2mf_x3j_herm_(const char*, dcomplex*);
void hprod_mkv2mf_x3j_poisson_(const char*, const dcomplex*, dcomplex*);
void hprod_mkv2mf_x3j_poissonp_(const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*, const int*, const int*, const int*);
void hprod_mkv2mf_x3j_poissonp2_(const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*, const int*, const int*, const int*);
void hprod_mpfock_(const double*, const dcomplex*, const dcomplex*);
void hprod_mpfock_sum_();
void hprod_mpfock_dft_(const double*, const dcomplex*);
void hprod_norb_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_norb2_(const dcomplex*, dcomplex*, double*);
void hprod_norb3_(dcomplex*, dcomplex*, double*);
void hprod_norb4_(dcomplex*, const dcomplex*, dcomplex*, double*);
void hprod_oang_(const dcomplex*, const dcomplex*, double*, double*);
void hprod_oang2_(const dcomplex*, const dcomplex*, const dcomplex*, double*);
void hprod_oangz_(const dcomplex*, double*);
void hprod_op1e_(const double*, const dcomplex*, const dcomplex*, double*);
void hprod_op1tr_(const double*, double*, double*, double*);
void hprod_op1tr_final_();
void hprod_op1tr_init_(const int*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_op1tr_nrad_(const dcomplex*);
void hprod_op1tr_opmat0_();
void hprod_op1tr_orbin_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_op2e_(const double*, const dcomplex*, const dcomplex*, double*);
void hprod_orbene_(const double*, const dcomplex*, const dcomplex*, double*);
void hprod_orbenex_(const bool*, dcomplex*, dcomplex*, double*);
void hprod_fcorb_(const double*, dcomplex*, dcomplex*);
void hprod_fcorbg_(const double*, dcomplex*);
void hprod_orbin_(const double*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_poisson1_(const dcomplex*, dcomplex*);
void hprod_poisson1p_(const dcomplex*, dcomplex*, const int*, const int*);
void hprod_ppop1_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, double*, double*);
void hprod_printorb_(const dcomplex*);
void hprod_printrho_(const dcomplex*);
void hprod_printrhog_(const dcomplex*);
void hprod_proj_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_proj2_(const int*, const int*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_projall_(const bool*, const dcomplex*, dcomplex*);
void hprod_projallp_fmat_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_projallp_proj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_projfc_(const bool*, const dcomplex*, dcomplex*);
void hprod_projfc2_(const bool*, const dcomplex*, dcomplex*);
void hprod_projfc2p_fmat_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_projfc2p_proj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_projfcp_fmat_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_projfcp_proj_(const bool*, const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_projhigh_(dcomplex*);
void hprod_projpp_(const dcomplex*, const double*, const dcomplex*, dcomplex*);
void hprod_pzprod_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
void hprod_pzprod_all_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_pzprod_dyn_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_pzprod_ecsout_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_pzprod_fc_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_pzprod_fc1_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_pzprod_fc2_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_pzprodp_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
void hprod_semicanonical_(dcomplex*);
void hprod_mkrhofc_ecs_(const dcomplex*, dcomplex*);
void hprod_mkv2jfc_ecs_(const dcomplex*, dcomplex*);
void hprod_symlm_(dcomplex*);
void hprod_tprod_(const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
void hprod_tprod_all_(const dcomplex*, dcomplex*);
void hprod_tprod_dyn_(const dcomplex*, dcomplex*);
void hprod_tprod_ecsout_(const dcomplex*, dcomplex*, const int*, const int*);
void hprod_tprod_ene_(const dcomplex*, dcomplex*);
void hprod_tprod_fc_(const dcomplex*, dcomplex*);
void hprod_tprod_fc1_(const dcomplex*, dcomplex*);
void hprod_tprod_fc2_(const dcomplex*, dcomplex*);
void hprod_tprodp_(const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
dcomplex hprod_trace1_(const bool*, const dcomplex*, const dcomplex*, const dcomplex*);
double hprod_trace1_pp_(const bool*, const double*, const dcomplex*, const dcomplex*, const dcomplex*);
void hprod_trans_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_transp_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*);
void hprod_v1ext_(const bool*, const dcomplex*, const double*, const dcomplex*, dcomplex*);
void hprod_v1tot_(const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_v1tot_mkint1_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mkrhofc_(const dcomplex*, dcomplex*);
void hprod_mkv2jfc_(const dcomplex*, dcomplex*);
void hprod_set_wfn0_(const dcomplex*, const dcomplex*, const char*, int);
void hprod_v2fc_(const dcomplex*, const dcomplex*, const char*);
void hprod_v2fc_enefc_(double*);
void hprod_v2fc_xkli_(dcomplex*);
void hprod_v2fc_xlda_(dcomplex*);
void hprod_v2xfc_opt1_(const dcomplex*, dcomplex*);
void hprod_v2xfc_opt2_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_xc_ldac_(dcomplex*, dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_xc_ldax_(dcomplex*, dcomplex*, dcomplex*, dcomplex*, dcomplex*);
void hprod_xcprod_(const bool*, dcomplex*, dcomplex*);
void hprod_zprod_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
void hprod_zprod_all_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_zprod_dyn_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_zprod_fc_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_zprod_fc1_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_zprod_fc2_(const dcomplex*, const dcomplex*, dcomplex*);
void hprod_zprodp_(const dcomplex*, const dcomplex*, dcomplex*, const int*, const int*, const int*, const int*);
void lapack_zgetri_(const int*, dcomplex*, dcomplex*);
void io_bind_(const char*, int);
void test_zaxpy_omp_();
void omp_mod_thread_(const int*, const int*);
void omp_mod_thread_str_(const int*, const int*);
double oncvpsp_ekb_(const int*, const int*);
double oncvpsp_getd1vloc_(const double*);
double oncvpsp_getproj_(const int*, const int*, const double*);
double oncvpsp_getvloc_(const double*);
void oncvpsp_init_(const char*);
int oncvpsp_maxl_();
int oncvpsp_nump_(const int*);
double oncvpsp_rcut_();
double oncvpsp_rmax_();
double ppatom_getd1vloc_(const int*, const double*);
double ppatom_getpfun_(const int*, const double*);
double ppatom_getsfun_(const int*, const double*);
double ppatom_getvloc_(const int*, const double*);
double ppatom_getvp_(const int*, const double*);
double ppatom_getvs_(const int*, const double*);
void ppatom_init_(const int*, const char*);
void ppatom_init1_(const int*, const char*, int*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*);
double ppatom_peig_(const int*);
double ppatom_rcut_(const int*);
double ppatom_rmax_(const int*);
double ppatom_rmin_(const int*);
double ppatom_seig_(const int*);
double tmpsp_ekb_(const int*);
double tmpsp_getd1vloc_(const double*);
double tmpsp_getproj_(const int*, const double*);
double tmpsp_getvloc_(const double*);
void tmpsp_init_(const char*);
int tmpsp_maxl_();
double tmpsp_rcut_();
double tmpsp_rmax_();
void mpi_omp_divide_(const int*, const int*, int*, int*);
int mpi_omp_nproc_();
int ormas_allowed_(const int*, const int*);
void ormas_arcwgt_();
void ormas_arcwgt_spin_(const int*, int*);
bool ormas_chkorth_(const int*, const int*, const int*, const int*, const int*, const int*);
void ormas_cic0_(dcomplex*);
void ormas_cic_print_(const dcomplex*, const char*, int);
void ormas_cic_print_old_(const dcomplex*, const char*);
void ormas_cic_printx_(const dcomplex*, const int*);
void ormas_denipd_(const int*, const dcomplex*, const dcomplex*, double*, dcomplex*);
void ormas_denipd_1_(dcomplex*, const dcomplex*, dcomplex*);
void ormas_denipx_(const int*, const dcomplex*, const dcomplex*, double*, dcomplex*);
void ormas_denipx_ras_(const int*, const dcomplex*, const dcomplex*, double*, dcomplex*);
dcomplex ormas_dets0_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dets1_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dets_single_(const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dett_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dett1_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dett2_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dett2_old_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dett3_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
dcomplex ormas_dett_1_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*);
void ormas_detu4_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_detu_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_detu0_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_detu1_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_detu2_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_detu3_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_detu_null_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_dist_();
void ormas_dist_itr_(const int*, const int*, const int*, const int*, int*, int*);
void ormas_dist_ndist_(const int*, const int*, const int*, const int*, int*);
void ormas_dist_next_(const int*, const int*, const int*, bool*, int*);
int ormas_elec2fun_(const int*, const int*, const int*, const int*);
void ormas_fab_();
void ormas_final_();
void ormas_hcic_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, const double*);
void ormas_zhcic_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_zhcicp_(const dcomplex*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1p_(const double*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_zhcic1_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1_old_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1_old_aap_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1_old_bbp_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1_ras_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1_ras_aap_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic1_ras_bbp_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_old_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_old_aap_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_old_abp_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_old_bbp_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_old_effint1e_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_old_effint2e_(const dcomplex*, dcomplex*);
void ormas_hcic_ras_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_ras_aap_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_ras_abp_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_ras_bbp_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_ras_effint1e_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_ras_effint2e_(const dcomplex*, dcomplex*);
void ormas_hcic_rasmat_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_rasmat_aap_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_rasmat_abp_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_rasmat_bbp_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_rasmat_effint1e_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hcic_rasmat_effint2e_(const dcomplex*, dcomplex*);
void ormas_hdiag_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hdiag_aap_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hdiag_abp_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hdiag_bbp_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_hdiag_effint1e_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_info_();
void ormas_init_(const int*, const int*);
void ormas_int1x_();
void ormas_int1x_order_(const int*, int*, int*, int*, int*);
void ormas_int1x_print_();
void ormas_int1x_print_spin_(const int*, const int*, const int*, const int*, const int*, const int*);
void ormas_int1x_spin_(const int*, const int*, const int*, const int*, const int*);
void ormas_int1xr_();
void ormas_int1xr_print_();
void ormas_int1xr_print_spin_(const int*, const int*, const int*, const int*, const int*, const int*, const int*);
void ormas_int1xr_spin_(const int*, const int*, const int*, const int*, const int*);
void ormas_ipd_(const int*, const dcomplex*, const dcomplex*, double*);
void ormas_ipx_(const int*, const dcomplex*, const dcomplex*, double*);
void ormas_ipx_core_(const int*, const dcomplex*, double*);
void ormas_ipx_old_(const int*, const dcomplex*, const dcomplex*, double*);
void ormas_ipx_ras_(const int*, const dcomplex*, const dcomplex*, double*);
void ormas_madapt_(const int*);
void ormas_madapt_int1x_spin_(const int*, const int*, const int*, const int*, const int*, const int*, int*, int*);
void ormas_madapt_str_(const int*);
void ormas_max1x_m_spin_(const int*, const int*, const int*, const int*, const int*, int*);
int ormas_map1x_(const int*, const int*, const int*, const int*, const int*);
int ormas_map1x_sub_(const int*, const int*, const int*, const int*);
void ormas_mkdden1_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkdden1_old_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkdden1_ras_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkdden1_ras_aa_(const dcomplex*, const dcomplex*, dcomplex*, const int*);
void ormas_mkdden1_ras_bb_(const dcomplex*, const dcomplex*, dcomplex*, const int*);
void ormas_mkden1_(const dcomplex*, dcomplex*);
void ormas_mkden1_full_(const dcomplex*, dcomplex*);
void ormas_mkden1_ion_(dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkden1_smat_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkden1_old_(const dcomplex*, dcomplex*);
void ormas_mkden1_old_bb_(const dcomplex*, dcomplex*, const int*);
void ormas_mkden1_ras_(const dcomplex*, dcomplex*);
void ormas_mkden1_ras_aa_(const dcomplex*, dcomplex*, const int*);
void ormas_mkden1_ras_bb_(const dcomplex*, dcomplex*, const int*);
void ormas_mkden2_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkden2_full_(const dcomplex*, dcomplex*);
void ormas_print_den2_(const dcomplex*);
void ormas_mkden2_old_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkden2_old_aap_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2_old_abp_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2_old_bap_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2_old_bbp_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2_old_sum_(const dcomplex*, const dcomplex*, dcomplex*, const int*);
void ormas_mkden2_ras_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkden2_ras_aap_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2_ras_abp_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2_ras_bbp_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2_ras_sum_(const dcomplex*, dcomplex*, dcomplex*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2x_(const dcomplex*, dcomplex*);
void ormas_mkden2x_old_(const dcomplex*, dcomplex*);
void ormas_mkden2x_old_abp_(const int*, const dcomplex*, dcomplex*);
void ormas_mkden2x_old_bbp_(const int*, const dcomplex*, dcomplex*);
void ormas_mkden2x_ras_(const dcomplex*, dcomplex*);
void ormas_mkden2x_ras_aap_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2x_ras_abp_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2x_ras_bbp_(const dcomplex*, const int*, dcomplex*, dcomplex*, const int*);
void ormas_mkden2x_ras_sum_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, const int*);
void ormas_mkidm_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkidm_old_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_mkidm_ras_(const dcomplex*, const dcomplex*, dcomplex*);
void ormas_occbc_();
void ormas_occbcx_();
void ormas_core_print_(const int*, const bool*);
void ormas_occvec_(const int*, const int*, const int*, const int*, int*);
void ormas_occvec_print_(const int*, const bool*, const int*, const int*);
void ormas_orbvec_(const int*, const int*, int*);
void ormas_orbvec_print_(const bool*, const int*, const int*);
void ormas_rm_singles_(dcomplex*);
void ormas_rotaa_();
void ormas_rotca_();
void ormas_rotoo_();
int ormas_sgn1x_(const int*, const int*, const int*, const int*);
void ormas_sgnperm2_(const int*, const int*, int*, int*, int*);
void ormas_sgnperm3_(const int*, const int*, const int*, int*, int*, int*, int*);
void ormas_sgnperm4_(const int*, const int*, const int*, const int*, int*, int*, int*, int*, int*);
void ormas_sgnperm5_(const int*, const int*, const int*, const int*, const int*, int*, int*, int*, int*, int*, int*);
void ormas_sij_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
void ormas_spin_(const dcomplex*, double*, double*);
void ormas_spin_old_(const dcomplex*, double*, double*);
void ormas_spin_old_s2_(const dcomplex*, double*);
void ormas_spin_ras_(const dcomplex*, double*, double*);
void ormas_spin_ras_s2_(const dcomplex*, double*);
void ormas_str_();
void ormas_str_spin_(const int*, const int*, const int*, int*);
void ormas_str_dot_str_0_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_0_0_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_0_1_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_0_2_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_0_3_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_0_4_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_1_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_1_0_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_1_1_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_1_2_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_1_3_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_str_dot_str_1_4_(const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_xact2_(const double*, const dcomplex*, const dcomplex*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_xact2x_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_xact2x_amat_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, double*);
void ormas_xact2x_bvec_(const double*, const dcomplex*, dcomplex*, double*);
void ormas_xact2x_solve_(const int*, dcomplex*, const dcomplex*, dcomplex*);
void ormas_xact2x_solver_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_xact2_donly_(const double*, const dcomplex*, const dcomplex*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void ormas_xact2x_donly_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_xact2x_donly_amat_(const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, double*);
void ormas_xact2x_donly_bvec_(const double*, const dcomplex*, dcomplex*, double*);
void pes_bind_(const int*, const int*, const int*, const double*, const double*, const double*, const double*, const dcomplex*, const dcomplex*);
void pes_spec1_k_(const dcomplex*, const dcomplex*);
void pes_spec1_k_psik_(const dcomplex*, dcomplex*);
void pes_spec1_k_rhok_(const dcomplex*, dcomplex*);
void pes_spec1_k_trace_(const dcomplex*, dcomplex*);
void pes_spec1_k_rhok_z_(const dcomplex*, dcomplex*);
void pes_spec1_kz_(const dcomplex*, const dcomplex*);
void adi_gen_tadi_(const int*, const int*, const int*, const double*, dcomplex*, dcomplex*, int*);
void adi_laser_lgauge_(const int*, const int*, const double*, const double*, dcomplex*);
void adi_laser_lgaugep_(const int*, const double*, const double*, dcomplex*, const int*);
void adi_laser_vgauge_(const int*, const int*, const double*, const double*, dcomplex*);
void adi_laser_vgauge_angp_(const int*, const double*, const double*, dcomplex*, const int*);
void adi_laser_vgauge_mixp_(const int*, const double*, const double*, dcomplex*, const int*);
void adi_t_explicit_(const dcomplex*, dcomplex*);
void adi_t_implicit_(const dcomplex*, const int*, dcomplex*);
void adi_v_cayley_(const int*, const double*, const double*, dcomplex*);
void adi_v_cayleyp_(const int*, const double*, const double*, const double*, dcomplex*, const int*, const int*);
void dpade_cnic_(const int*, const int*, const int*, const int*, const double*, const double*, const dcomplex*, const int*, const double*, const int*, const dcomplex*, dcomplex*);
void dpade_gen_(const int*, const double*, const dcomplex*, dcomplex*, int*);
void dpade_gen2_(const dcomplex*, const dcomplex*, dcomplex*, int*);
void dpade_h0inv_(const int*, const dcomplex*, dcomplex*);
void dpade_prod_(const int*, const int*, const int*, const int*, const double*, const double*, const dcomplex*, const int*, const double*, const int*, const dcomplex*, dcomplex*);
void dpade_prod_fcore_(const dcomplex*, dcomplex*);
void dpade_prod_fcrot_(const double*, const double*, dcomplex*);
void dpade_h0inv2_(const int*, const dcomplex*, dcomplex*);
void dpade_prod2_(const int*, const int*, const double*, const dcomplex*, const int*, const double*, const int*, const dcomplex*, dcomplex*);
void dpade_prod_fcore2_(const dcomplex*, dcomplex*);
void h1exp_exporb_(const int*, const double*, const int*, const int*, const double*, const double*, const dcomplex*, dcomplex*);
void h1exp_exporb1_(const int*, const double*, const int*, const int*, const double*, const dcomplex*, const dcomplex*, const int*, const int*, dcomplex*);
void h1exp_krylov_(const int*, const int*, const double*, const double*, const int*, const double*, const dcomplex*, int*, double*, double*, dcomplex*);
void h1exp_krylov1_(const int*, const int*, const double*, const int*, const int*, const int*, const int*, const dcomplex*, int*, double*, dcomplex*, dcomplex*);
double h1exp_krylov_error_(const int*, const double*, const double*, const double*);
void h1exp_mmap_(int*, int*, int*);
void h1exp_prop_(const int*, const int*, const int*, const double*, const double*, const int*, const double*, dcomplex*);
void h1exp_prop1_(const int*, const int*, const int*, const double*, const double*, const int*, dcomplex*);
void h1itr_cninv_(const int*, const dcomplex*, dcomplex*);
void h1itr_gen_cninv_(const int*, const double*, int*, dcomplex*);
void h1itr_gen_cninv2_(const int*, const double*, int*, dcomplex*);
void h1itr_prop_(const int*, const int*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const dcomplex*, dcomplex*);
void h1itr_prop_fcore_(const dcomplex*, dcomplex*);
void h1itr_prop_fcrot_(const double*, const double*, dcomplex*);
void h1itr_prop2_(const int*, const int*, const int*, const double*, const double*, const double*, const int*, const double*, const int*, const dcomplex*, dcomplex*);
void h1itr_prop2_fcore_(const dcomplex*, dcomplex*);
void h1rat_gen_(const int*, const dcomplex*, const dcomplex*, dcomplex*, int*);
void h1rat_h0inv_(const int*, const dcomplex*, dcomplex*);
void h1rat_h0inv_v2_(const int*, const dcomplex*, dcomplex*);
void h1rat_prod_(const bool*, const bool*, const double*, const double*, const int*, const int*, const dcomplex*, const dcomplex*, const int*, const dcomplex*, dcomplex*);
void h1rat_prod_numer_(const double*, const double*, const int*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void h1rat_prodci_(const bool*, const bool*, const dcomplex*, const double*, const int*, const int*, const dcomplex*, const dcomplex*, const dcomplex*, const int*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void h1rat_prodci1_(const bool*, const bool*, const dcomplex*, const double*, const int*, const int*, const dcomplex*, const dcomplex*, const dcomplex*, const int*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void h1rat_hcic_(const dcomplex*, dcomplex*);
void h1rat_hcic1_(const dcomplex*, dcomplex*);
void h1rat_prodci2_(const bool*, const bool*, const dcomplex*, const double*, const int*, const int*, const dcomplex*, const dcomplex*, const dcomplex*, const int*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void pade_gen_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const double*, const dcomplex*, const double*, const double*, dcomplex*, int*);
void pade_gen2_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const double*, const dcomplex*, const double*, const double*, dcomplex*, int*);
void sph_3j_final_();
void sph_3j_init_();
void sph_gen_(const int*, const int*, const int*, const int*, const int*, const int*, double*, double*, double*, double*, double*, double*, double*, double*, double*);
void sph_gen_x3j_(const int*, const int*, const int*, const int*, const int*, const int*, double*, double*, double*, double*, double*, double*, double*, double*, double*);
void calc_orb_(const int*, const dcomplex*, dcomplex*, dcomplex*);
void calc_orbp_(const int*, const int*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void surff_rec_v2xmat_(dcomplex*);
double util_3j000_(const int*, const int*, const int*);
void util_arnoldi_(const double*, const int*, const int*, const double*, int*, dcomplex*, dcomplex*, dcomplex*);
double util_arnoldi_error_(const int*, const int*, const dcomplex*, const double*, const double*);
int util_bicoeff_(const int*, const int*);
void util_zaxpy_(const int*, const dcomplex*, const dcomplex*, const int*, dcomplex*, const int*);
void util_zcopy_(const int*, const dcomplex*, const int*, dcomplex*, const int*);
dcomplex util_zdotc_(const int*, const dcomplex*, const int*, const dcomplex*, const int*);
dcomplex util_zdotcp_(const int*, const dcomplex*, const dcomplex*);
dcomplex util_zdotu_(const int*, const dcomplex*, const int*, const dcomplex*, const int*);
dcomplex util_zdotup_(const int*, const dcomplex*, const dcomplex*);
void util_zscal_(const int*, const dcomplex*, dcomplex*, const int*);
dcomplex util_det_(const int*, const double*, const dcomplex*);
void util_diag_comp_(const bool*, const int*, dcomplex*, dcomplex*);
void util_diag_comp2_(const bool*, const int*, const dcomplex*, dcomplex*, dcomplex*);
void util_diag_real_(const bool*, const int*, double*, double*);
void util_diag_real2_(const bool*, const int*, const double*, double*, double*);
void util_zexpax_(const int*, const dcomplex*, dcomplex*, dcomplex*);
long double util_fact_(const int*);
void util_gdiag_(const bool*, const int*, dcomplex*, dcomplex*, dcomplex*);
void util_gexphd_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void util_gmatinv_(const int*, const double*, const dcomplex*, dcomplex*);
void util_gmatinv_real_(const int*, const double*, const double*, double*);
int util_ifact_(const int*, const int*);
void util_krylov_(const double*, const int*, const int*, const double*, int*, double*, double*, double*, dcomplex*, dcomplex*);
double util_krylov_error_(const int*, const double*, const double*, const double*);
void util_matinv_reg_(const int*, const double*, const dcomplex*, dcomplex*);
void util_matinv_reg_real_(const int*, const double*, const double*, double*);
void util_linoutc_(const int*, const dcomplex*);
void util_matoutc_(const int*, const dcomplex*);
void util_matoutc2_(const int*, const int*, const dcomplex*);
void util_omp_disp_(const int*, const int*, int*, int*);
void util_omp_disp_top_(const int*, const int*, const int*, const int*, int*, int*);
void util_omp_gather_(const int*, const dcomplex*, dcomplex*);
int util_omp_iproc_();
int util_omp_nproc_();
void util_print_vec_(const int*, const dcomplex*, const char*);
void util_svd_real_(const int*, const int*, const double*, double*, double*, double*);
void util_trimat_(const int*, const double*, int*, dcomplex*);
void util_window1_(const int*, const int*, const int*, const dcomplex*, dcomplex*);
void util_window2_(const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
void util_window3_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
void util_window4_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
void util_window5_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const dcomplex*, dcomplex*);
void util_youla_ceig_(const int*, const dcomplex*, dcomplex*, dcomplex*);
void util_youla_real_(const int*, const double*, double*, double*, double*);
void util_youla_reig_(const int*, const dcomplex*, dcomplex*, dcomplex*);
void wfn_ladapt_(dcomplex*, dcomplex*);
void wfn_ladapt_core_(dcomplex*);
void wfn_ladaptc_(dcomplex*);
void wfn_ladapto_(dcomplex*);
void wfn_ladapt_old_(dcomplex*);
void wfn_ladapt_old_core_(dcomplex*);
void wfn_madapt_(dcomplex*);
void wfn_mask_(dcomplex*);
void wfn_orth_cic_(dcomplex*);
void wfn_orth_orb_(dcomplex*);
void wfn_orth_orb_symm_(dcomplex*);
void wfn_orth_smat_(const dcomplex*, dcomplex*);
void wfn_proj_(const dcomplex*, dcomplex*);
void wfn_projg_(const dcomplex*, dcomplex*);
void lapack_dsyev_(const int*, double*, double*);
void lapack_zheev_(const int*, dcomplex*, dcomplex*);
void lapack_zheev_dsc_(const int*, dcomplex*, dcomplex*);
void lapack_zgesv_(const int*, const int*, dcomplex*, dcomplex*);
void lapack_zhesv_(const int*, const int*, dcomplex*, dcomplex*);
void zadd_omp_(const int*, const dcomplex*, dcomplex*);
void zaxpbyz_omp_(const int*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void zaxpy_omp_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void zaxpyz_omp_(const int*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void dclear_omp_(const int*, double*);
void zclear_omp_(const int*, dcomplex*);
void zcopy_omp_(const int*, const dcomplex*, dcomplex*);
void zdotc_omp_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void dscal_omp_(const int*, const double*, double*);
void zscal2_omp_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void zscal_omp_(const int*, const dcomplex*, dcomplex*);
void zxmyz_omp_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void zxpy_omp_(const int*, const dcomplex*, dcomplex*);
void zxpyz_omp_(const int*, const dcomplex*, const dcomplex*, dcomplex*);
void ormas_bind_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, int*, int*, int*, int*, int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const double*, const bool*, const bool*, const bool*, const bool*, const int*, const int*, const int*, const bool*, const int*, const char*, int);
void control_bind_(const int*, const int*, const int*, const int*, const int*, const int*, const bool*, const bool*, const int*, const double*, const bool*, const bool*, const bool*, const bool*, const int*, const int*, const int*, const double*, const double*, const double*, const int*, const int*, const double*, const int*, const bool*, const bool*, const bool*, const bool*);
void hprod_dipole_tdcis_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*, dcomplex*, dcomplex*);
dcomplex hprod_trace2_tdcis_(const double*, const dcomplex*, const dcomplex*);
dcomplex hprod_trace_tdcis_(const dcomplex*);
void hprod_htot_dtorb_tdcis_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_htot_dtorb_tdcis_rvg_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_htot_tdcis_(const double*, const double*, const dcomplex*, const dcomplex*, dcomplex*, dcomplex*);
void hprod_htotx_tdcis_(const double*, const double*, const dcomplex*, const dcomplex*);
void hprod_mfprod2_tdcis_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_mkrho2_tdcis_();
void hprod_mkrho2_tdcis_init_();
void hprod_mkv2mf_herm_tdcis_(dcomplex*);
void hprod_mkv2mf_poissonp_tdcis_(const dcomplex*, dcomplex*, const int*, const int*);
void hprod_mkv2mf_poissonp_tdcis_init_(const dcomplex*, dcomplex*, const int*, const int*);
void hprod_mkv2mf_tdcis_();
void hprod_mkv2mf_tdcis_init_();
void subroutine_(const dcomplex*, dcomplex*, const int*, const int*);
void hprod_acc_add_tdcis_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_dotop1e_tdcis_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_op1e_tdcis_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_op1e_tdcis_old_(const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_vel_add_tdcis_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_dotorb_tdcis_(const double*, const dcomplex*, const dcomplex*, const dcomplex*, dcomplex*);
void hprod_phys_tdcis_(const double*, const double*, const double*, const dcomplex*, const dcomplex*, double*, double*, double*);
void hprod_dotorb_tdcis_debug_(const double*, const dcomplex*, const dcomplex*);
void hprod_phys_tdcis_debug_(const double*, const double*, const double*, const dcomplex*, const dcomplex*, double*, double*, double*);
void hprod_popgs_tdcis_(const dcomplex*);
void hprod_fcorbg_tdcis_(const double*);
void hprod_orbin_tdcis_(const double*);
void hprod_orbin_tdcis_init_();
void bas_bas_bind_(const int*, const int*, const int*, const int*, const int*, int*, int*, int*, int*, int*, int*, const double*, const double*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, const double*, const dcomplex*, const dcomplex*, const dcomplex*, const dcomplex*, const double*, const double*, const double*, const double*, const double*, const dcomplex*, const int*, const dcomplex*, const dcomplex*, const double*, const dcomplex*, const int*);
void bas_rad_bind_(const int*, const int*, const int*, const int*, const int*, const int*, const double*, const double*, const double*, const double*, const double*, const double*, const double*, const int*, const double*, const double*, const dcomplex*, const dcomplex*, const int*, const dcomplex*, const double*, const dcomplex*, const dcomplex*, const int*, const int*, const int*, const int*, const bool*, const int*, const double*, const int*, const int*, const int*, const int*, const int*);
void bas_sph_bind_(const int*, const int*, const int*, const int*, const int*, const int*, const int*, const int*, const double*, const double*, const double*, const double*, const double*, const double*, const double*, const double*, const double*, const int*, const int*);
void ormas_bind_tdcis_(const int*);
void wfn_get_nradfc_(const dcomplex*);
void wfn_set_nradgs_(const int*, const int*, const int*);
// END
}
//////////////////////////////////////////////////////////////////////
#endif
